[package]
name = "test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
hex = "0.4.3"
lazy_static = "1.4.0"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.11"
