name: Setup
description: setup rust toolchains, checkout, and restore cache

runs:
  using: "composite"
  steps:
    - name: get toolchains
      run: |
        rustup set auto-self-update disable
        rustup toolchain install stable --profile minimal
        rustup target add x86_64-pc-windows-gnu x86_64-apple-darwin x86_64-unknown-linux-gnu
        sudo apt-get install -y gcc-mingw-w64
      shell: bash

    - name: setup osxcross
      uses: mbround18/setup-osxcross@main
      with:
        osx-version: "12.3"

    - name: checkout
      uses: actions/checkout@v3

    - name: cache rust
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: cache01
